version: '3'

services:
  apache:
    build:
      dockerfile: Dockerfile
      context: ./php7
    image: php/php:7.4-apache
    container_name: php7-apache2
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root